version: "3"
services:
  mosquitto:
    image: sbx-mosquitto
    container_name: mosquitto
    volumes:
      - LOCAL_PATH_CONFIG:/mosquitto/config
      - LOCAL_PATH_DATA:/mosquitto/data
      - LOCAL_PATH_LOG:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001
    restart: unless-stopped
